### ISSUE TITLE
Missing String to be translated "Search Contacts"

### ISSUE THREAD

**Issue by fiazk** [NewEconomyMovement/NEMiOSApp#182]
This string is not available in the translation table.

![photo_2016-04-04_00-44-16](https://cloud.githubusercontent.com/assets/17099341/14235437/83f35e54-f9fe-11e5-93bd-91e5ef17588d.jpg)

Mobile: Samsung S3
Android 4.3
NEM 2.0
NEM Address if bounty is applicable: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 32 BETA

String added to google-doc

**Comment by jabo38** [comment]
Transaction hash: 28cd9f67b3b0e3b61e722fc5550973f73b0b9708e725b7e5c16ea320e8d7713b
 Bounty paid.

**Comment by fiazk** [comment]
@jabo38 @fyahfox could some please check if this was fixed? or at least send me ss again, thanks

**Comment by jabo38** [comment]
so for other languages it is not working.  I was under the assumption the strings had all been updated but it seems to still not work so I am undoing mustfix.  I'm guessing somehow the strings were not updated.

**Comment by jabo38** [comment]
update from Mixmaster.  the strings will be updated soon.

**Comment by LyubomirDominik** [comment]
This issue is fixed and will be displaying as "Search Contacts" in English localization or "SEARCH_CONTACTS" in other languages before you provide us with localization files

**Comment by fyahfox** [comment]
Can somebody confirm this fixed? The updated strings should be in the lastest version (right @LyubomirDominik ?).

**Comment by fiazk** [comment]
it seems this was never added to the loc. files. @fyahfox @jabo38

**Comment by fyahfox** [comment]
I do see the string in the tables... So maybe at the time you checked, it was simply not translated yet, @fiazk ?
