### ISSUE TITLE
Can't scan QRs from Android for Private Key, Invoices, or Address Book.  

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#36]
Tested the QRs from Android on iOS.  Private Key won't scan.  Invoices crash the phone.  Address book doesn't give account. 

Android can't scan iOS accounts too.

**Comment by fyahfox** [comment]
this is better now, but still not 100% working. i cant really speak for iOs though.

**Comment by LyubomirDominik** [comment]
Can you please be more specific?

**Comment by fyahfox** [comment]
we talked about this in the skype call...? it is just not working yet. you had crashes too.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 8 
But appear bug connected with notifications, which fixed in Version  Build 9
In Version 2 Build 8, QR works good but not for a new accounts
Version 2 Build 9, QR only compatible with Android version 0.1.27

**Comment by jabo38** [comment]
Version 2.9 of iOS and 0.1.27 in Android are not compatible still.

**Comment by fyahfox** [comment]
"In Version 2 Build 8, QR works good but not for a new accounts"
i dont understand what you mean with this

**Comment by jabo38** [comment]
to be clear iOS can't scan any QR from android

**Comment by LyubomirDominik** [comment]
"In Version 2 Build 8, QR works good but not for a new accounts"
i dont understand what you mean with this

I mean that if public key of an account don't known by the NCC app use to crash but in Version 2 Build 9 it was fixed

**Comment by LyubomirDominik** [comment]
scan QR in IOS works good, problem is in Android. Will be fixed in next Android build.

**Comment by fyahfox** [comment]
ok so if you think everything is fixed on the iOs side, you can lable this issue "resolved".
we will close it, if we can confirm that it is fixed.

**Comment by jabo38** [comment]
iOS can now scan all Android QRs and all iOS QRs.  :-)   (Android still can't scan anything though)
